#############################################################################
# Default values are used if any of the following is not specified.         #
# Look at the function `initialize` in `solver.cpp` for the default values. #
#############################################################################

[grid]

# currently have no effect
type = "solovev"

# The number of points in the r direction
N = 100


# The default format is chosen automatically
# depending on the availability of libraries.
[output]

# "netCDF" and "csv" are supported.
# The case does not matter.
# format = "netCDF"

name = "polynomial.nc"
print = false

[solver] 

# relative error for the fixed-point iteration
e_fix = 1e-6

# relative error for Succesive Over Relaxation
e_sor = 1e-8
# relaxation coefficient. Diverges if ≥ 2.
omega = 1.8

# relative error for the minimum at the normalization step
e_min = 1e-6

# The total current
I_p = 500e3

# psi at the computational boundary
psi_l = 1

# psi at the physical plasma boudnary
psi_bdry = 0.1

[initial_condition]

# Choose p(psi) and g(psi)
# "solovev" and "polynomial" are supported.
type = "polynomial"
beta0 = 0.1
m = 2
n = 1


