#############################################################################
# Default values are used if any of the following is not specified.         #
# Look at the function `initialize` in `solver.cpp` for the default values. #
#############################################################################

select = "blender"

[grid]

# currently have no effect
type = "solovev"

# The number of points in the r direction
N = 100


# The default format is chosen automatically
# depending on the availability of libraries.
[output]

# "netCDF" and "csv" are supported.
# The case does not matter.
# format = "netCDF"

name = "hmode_output.nc"
verbose = false
print_psi = false

N_gr = 17
logh_low = -2.4
delta_logh = 0.1

[solver] 

# relative error for the fixed-point iteration
# maximum 1e-14, usual 1e-8
e_fix = 1e-10

# relative error for Succesive Over Relaxation
# it suddenly takes very long if e_sor < 1e-14
# it turns out low e_sor converges faster overall!
# although it takes more iteration if it is too low.
e_sor = 1e-5

# relaxation coefficient. Diverges if ≥ 2.
# fast but imprecise if close to 2, slow but precise close to 1
omega = 1.8

# relative error for the minimum at the normalization step
e_min = 1e-11

# The total current
# I_p = 500e3
I_p = 1000
# psi at the computational boundary
psi_l = 1

# psi at the physical plasma boudnary
psi_bdry = 0.1

normalize = false
sigma0 = 1e4

[initial_condition]

# Choose p(psi) and g(psi)
# "solovev", "polynomial", "HMode" are supported.
type = "hmode"
beta0 = 0.5
m = 2
n = 1


