#############################################################################
# Default values are used if any of the following is not specified.         #
# Look at the function `initialize` in `solver.cpp` for the default values. #
#############################################################################

select = "polynomial"

[grid]

# currently have no effect
type = "solovev"

# The number of points in the r direction
N = 50


# The default format is chosen automatically
# depending on the availability of libraries.
[output]

# "netCDF" and "csv" are supported.
# The case does not matter.
# format = "netCDF"

name = "test.nc"
print = false

N_gr = 17
logh_low = -2.4
delta_logh = 0.1

[solver] 

# relative error for the fixed-point iteration
e_fix = 1e-13

# relative error for Succesive Over Relaxation
# it suddenly takes very long if e_sor < 1e-14
e_sor = 1e-14

# relaxation coefficient. Diverges if ≥ 2.
# fast but imprecise if close to 2, slow but precise close to 1
omega = 1.5

# relative error for the minimum at the normalization step
e_min = 1e-14

# The total current
I_p = 500e3

# psi at the computational boundary
psi_l = 1

# psi at the physical plasma boudnary
psi_bdry = 0.1

[initial_condition]

# Choose p(psi) and g(psi)
# "solovev" and "polynomial" are supported.
type = "polynomial"
beta0 = 0.5
m = 2
n = 1


